Config = Config or {}

Config.RosterLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/1J5Pr44sMEj47uSPkUC9GrfQDWCv7TfoHYNxdLfHrlPU/edit#gid=0',
    ['ambulance'] = '',
    ['sheriff'] = 'https://docs.google.com/spreadsheets/d/1J5Pr44sMEj47uSPkUC9GrfQDWCv7TfoHYNxdLfHrlPU/edit#gid=784326999',
    ['doj'] = '',
}

Config.OnlyShowOnDuty = true

Config.Fuel = "ps-fuel" -- "LegacyFuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'OFFENSES AGAINST PERSONS',
    [2] = 'OFFENSES INVOLVING THEFT',
    [3] = 'OFFENSES INVOLVING FRAUD',
    [4] = 'OFFENSES INVOLVING DAMAGE TO PROPERTY',
    [5] = 'OFFENSES AGAINST PUBLIC ADMINISTRATION',
    [6] = 'OFFENSES AGAINST PUBLIC ORDER',
    [7] = 'OFFENSES AGAINST HEALTH AND MORALS',
    [8] = 'OFFENSES AGAINST PUBLIC SAFETY',
    [9] = 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE',
    [10] = 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE',
    [11] = 'OFFENSES AGAINST THE STATE',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Simple Assault', class = 'Misdemeanor', id = 'P.C. 1001', months = 10, fine = 500, color = 'orange'},
        [2] = {title = 'Assault', class = 'Misdemeanor', id = 'P.C. 1002', months = 15, fine = 1800, color = 'orange'},
        [3] = {title = 'Aggravated Assault', class = 'Felony', id = 'P.C. 1003', months = 15, fine = 1800, color = 'red'},
        [4] = {title = 'Assault with a Deadly Weapon', class = 'Felony', id = 'P.C. 1004', months = 20, fine = 2500, color = 'red'},
        [5] = {title = 'Involuntary Manslaughter', class = 'Felony', id = 'P.C. 1005', months = 20, fine = 2000, color = 'red'},
        [6] = {title = 'Vehicular Manslaughter', class = 'Felony', id = 'P.C. 1006', months = 25, fine = 2500, color = 'red'},
        [7] = {title = 'Attempted Second Degree Murder', class = 'Felony', id = 'P.C. 1007', months = 30, fine = 3750, color = 'red'},
        [8] = {title = 'Second Degree Murder', class = 'Felony', id = 'P.C. 1008', months = 50, fine = 6000, color = 'red'},
        [9] = {title = 'Accomplice to Second Degree Murder', class = 'Felony', id = 'P.C. 1009', months = 40, fine = 4500, color = 'red'},
        [10] = {title = 'First Degree Murder', class = 'Felony', id = 'P.C. 1010', months = 70, fine = 7750, color = 'red'},
        [11] = {title = 'Accomplice to First Degree Murder', class = 'Felony', id = 'P.C. 1011', months = 55, fine = 5250, color = 'red'},
        [12] = {title = 'Attempted First Degree Murder', class = 'Felony', id = 'P.C. 1012', months = 60, fine = 6000, color = 'red'}, 
        [13] = {title = 'Unlawful Imprisonment', class = 'Misdemeanor', id = 'P.C. 1013', months = 10, fine = 500, color = 'orange'},
        [14] = {title = 'Kidnapping', class = 'Felony', id = 'P.C. 1014', months = 15, fine = 800, color = 'red'},
        [15] = {title = 'Accomplice to Kidnapping', class = 'Felony', id = 'P.C. 1015', months = 7, fine = 400, color = 'red'},
        [16] = {title = 'Attempted Kidnapping', class = 'Felony', id = 'P.C. 1016', months = 10, fine = 450, color = 'red'},
        [17] = {title = 'Hostage Taking', class = 'Felony', id = 'P.C. 1017', months = 20, fine = 1000, color = 'red'},
        [18] = {title = 'Accomplice to Hostage Taking', class = 'Felony', id = 'P.C. 1018', months = 10, fine = 600, color = 'red'},
        [19] = {title = 'Unlawful Imprisonment of a Public Servant or Peace Officer.', class = 'Felony', id = 'P.C. 1019', months = 25, fine = 2500, color = 'red'},
        [20] = {title = 'Criminal Threats', class = 'Misdemeanor', id = 'P.C. 1020', months = 5, fine = 200, color = 'orange'},
        [21] = {title = 'Reckless Endangerment', class = 'Misdemeanor', id = 'P.C. 1021', months = 10, fine = 800, color = 'orange'},
        [22] = {title = 'Gang Related Shooting', class = 'Felony', id = 'P.C. 1022', months = 30, fine = 2500, color = 'red'},
        [23] = {title = 'Cannibalism', class = 'Felony', id = 'P.C. 1023', months = 30, fine = 4000, color = 'red'},
        [24] = {title = 'Torture', class = 'Felony', id = 'P.C. 1024', months = 35, fine = 4000, color = 'red'},
        [25] = {title = 'Contract Killing', class = 'Felony', id = 'P.C. 1025', months = 65, fine = 6500, color = 'red'},
    },
    [2] = {
        [1] = {title = 'Petty Theft', class = 'Infraction', id = 'P.C. 2001', months = 0, fine = 300, color = 'green'},
	    [2] = {title = 'Theft', class = 'Misdemeanor', id = 'P.C. 2002', months = 10, fine = 1000, color = 'orange'},
        [3] = {title = 'Grand Theft', class = 'Felony', id = 'P.C. 2003', months = 10, fine = 1000, color = 'red'},
        [4] = {title = 'Grand Theft Auto', class = 'Felony', id = 'P.C. 2004', months = 35, fine = 3500, color = 'red'},
        [5] = {title = 'Carjacking', class = 'Felony', id = 'P.C. 2005', months = 35, fine = 3500, color = 'red'},
        [6] = {title = 'Burglary', class = 'Misdemeanor', id = 'P.C. 2006', months = 10, fine = 1000, color = 'orange'},
	    [7] = {title = 'Accomplice to Burglary', class = 'Felony', id = 'P.C. 2007', months = 5, fine = 500, color = 'red'},
        [8] = {title = 'Robbery', class = 'Felony', id = 'P.C. 2008', months = 25, fine = 2000, color = 'red'},
        [9] = {title = 'Accomplice to Robbery', class = 'Felony', id = 'P.C. 2009', months = 12, fine = 1000, color = 'red'},
        [10] = {title = 'Attempted Robbery', class = 'Felony', id = 'P.C. 2010', months = 20, fine = 1000, color = 'red'},
        [11] = {title = 'Armed Robbery', class = 'Felony', id = 'P.C. 2011', months = 30, fine = 3500, color = 'red'},
        [12] = {title = 'Accomplice to Armed Robbery', class = 'Felony', id = 'P.C. 2012', months = 15, fine = 1500, color = 'red'},
        [13] = {title = 'Attempted Armed Robbery', class = 'Felony', id = 'P.C. 2013', months = 25, fine = 1500, color = 'red'},
        [14] = {title = 'Grand Larceny', class = 'Felony', id = 'P.C. 2014', months = 20, fine = 4000, color = 'red'},
        [15] = {title = 'Leaving Without Paying', class = 'Infraction', id = 'P.C. 2015', months = 0, fine = 500, color = 'green'},
        [16] = {title = 'Possession of Nonlegal Currency', class = 'Misdemeanor', id = 'P.C. 2016', months = 10, fine = 750, color = 'orange'},
        [17] = {title = 'Possession of Government-Issued Items', class = 'Misdemeanor', id = 'P.C. 2017', months = 15, fine = 1500, color = 'orange'},
        [18] = {title = 'Possession of Items Used in the Commission of a Crime', class = 'Misdemeanor', id = 'P.C. 2018', months = 10, fine = 500, color = 'red'},
        [19] = {title = 'Theft of an Aircraft', class = 'Felony', id = 'P.C. 2019', months = 30, fine = 3000, color = 'red'},
    },
    [3] = {
        [1] = {title = 'Impersonating', class = 'Misdemeanor', id = 'P.C. 3001', months = 10, fine = 750, color = 'orange'},
        [2] = {title = 'Impersonating a Peace Officer or Public Servant', class = 'Felony', id = 'P.C. 3002', months = 25, fine = 2500, color = 'red'},
        [3] = {title = 'Impersonating a Judge', class = 'Felony', id = 'P.C. 3003', months = 35, fine = 2750, color = 'red'},
        [4] = {title = 'Possession of Stolen Identification', class = 'Misdemeanor', id = 'P.C. 3004', months = 10, fine = 750, color = 'orange'},
        [5] = {title = 'Possession of Stolen Government Identification', class = 'Misdemeanor', id = 'P.C. 3005', months = 20, fine = 2000, color = 'orange'},
        [6] = {title = 'Extortion', class = 'Felony', id = 'P.C. 3006', months = 20, fine = 1000, color = 'red'},
        [7] = {title = 'Fraud', class = 'Misdemeanor', id = 'P.C. 3007', months = 15, fine = 1000, color = 'orange'},
        [8] = {title = 'Forgery', class = 'Misdemeanor', id = 'P.C. 3008', months = 15, fine = 750, color = 'orange'},
        [9] = {title = 'Money Laundering', class = 'Felony', id = 'P.C. 3009', months = 40, fine = 2500, color = 'red'},
    },
    [4] = {
        [1] = {title = 'Trespassing', class = 'Misdemeanor', id = 'P.C. 4001', months = 10, fine = 450, color = 'orange'},
        [2] = {title = 'Felony Trespassing', class = 'Felony', id = 'P.C. 4002', months = 15, fine = 1500, color = 'red'},
        [3] = {title = 'Arson', class = 'Felony', id = 'P.C. 4003', months = 20, fine = 2000, color = 'red'},
        [4] = {title = 'Accomplice to Arson', class = 'Felony', id = 'P.C. 4004', months = 15, fine = 1500, color = 'red'},
        [5] = {title = 'Accessory to Arson', class = 'Felony', id = 'P.C. 4005', months = 10, fine = 1000, color = 'red'},
        [6] = {title = 'Vandalism', class = 'Misdemeanor', id = 'P.C. 4006', months = 0, fine = 300, color = 'orange'},
        [7] = {title = 'Vandalism of Government Property', class = 'Felony', id = 'P.C. 4007', months = 15, fine = 1000, color = 'red'},
        [8] = {title = 'Littering', class = 'Infraction', id = 'P.C. 4008', months = 0, fine = 50, color = 'green'},
        [9] = {title = 'Jaywalking', class = 'Infraction', id = 'P.C. 4009', months = 0, fine = 20, color = 'green'},
    },
    [5] = {
        [1] = {title = 'Bribery of a Government Official', class = 'Felony', id = 'P.C. 5001', months = 20, fine = 2000, color = 'red'},
        [2] = {title = 'Attempted Bribery of a Government Official', class = 'Felony', id = 'P.C. 5002', months = 15, fine = 1500, color = 'red'},
        [3] = {title = 'Anti-Mask Law', class = 'Infraction', id = 'P.C. 5003', months = 0, fine = 750, color = 'green'},
        [4] = {title = 'Possession of Contraband in a Government Facility', class = 'Felony', id = 'P.C. 5004', months = 20, fine = 1000, color = 'red'},
        [5] = {title = 'Criminal Possession of Stolen Property', class = 'Misdemeanor', id = 'P.C. 5005', months = 10, fine = 1000, color = 'orange'},
        [6] = {title = 'Escaping Custody', class = 'Felony', id = 'P.C. 5006', months = 10, fine = 450, color = 'red'},
        [7] = {title = 'Prison break', class = 'Felony', id = 'P.C. 5007', months = 30, fine = 2500, color = 'red'},
        [8] = {title = 'Accomplice to Prison Break', class = 'Felony', id = 'P.C. 5008', months = 25, fine = 2000, color = 'red'},
        [9] = {title = 'Accessory to Prison Break', class = 'Felony', id = 'P.C. 5009', months = 20, fine = 1500, color = 'red'},
        [10] = {title = 'Attempted Prison Break', class = 'Felony', id = 'P.C. 5010', months = 20, fine = 1500, color = 'red'},
        [11] = {title = 'Perjury', class = 'Felony', id = 'P.C. 5011', months = 30, fine = 2500, color = 'red'},
        [12] = {title = 'Violation of a Restraining Order', class = 'Felony', id = 'P.C. 5012', months = 20, fine = 2250, color = 'red'},
        [13] = {title = 'Embezzlement', class = 'Felony', id = 'P.C. 5013', months = 45, fine = 8000, color = 'red'},
        [14] = {title = 'Unlawful Practice', class = 'Felony', id = 'P.C. 5014', months = 15, fine = 1500, color = 'red'},
        [15] = {title = 'Misuse of Emergency Systems', class = 'Infraction', id = 'P.C. 5015', months = 0, fine = 600, color = 'green'},
        [16] = {title = 'Conspiracy', class = 'Misdemeanor', id = 'P.C. 5016', months = 10, fine = 450, color = 'orange'},
        [17] = {title = 'Violating a Court Order', class = 'Misdemeanor', id = 'P.C. 5017', months = 30, fine = 2500, color = 'orange'},
        [18] = {title = 'Failure to Appear', class = 'Misdemeanor', id = 'P.C. 5018', months = 30, fine = 2500, color = 'orange'},
        [19] = {title = 'Contempt of Court', class = 'Felony', id = 'P.C. 5019', months = 20, fine = 1500, color = 'red'},
        [20] = {title = 'Resisting Arrest', class = 'Misdemeanor', id = 'P.C. 5020', months = 10, fine = 1000, color = 'orange'},
        [21] = {title = 'Violation of Bail', class = 'Felony', id = 'P.C. 5021', months = 25, fine = 2500, color = 'red'},
    },
    [6] = {
        [1] = {title = 'Disobeying a Peace Officer', class = 'infraction', id = 'P.C. 6001', months = 0, fine = 750, color = 'green'},
        [2] = {title = 'Disorderly Conduct', class = 'Infraction', id = 'P.C. 6002', months = 0, fine = 250, color = 'green'},
        [3] = {title = 'Disturbing the Peace', class = 'infraction', id = 'P.C. 6003', months = 0, fine = 350, color = 'green'},
        [4] = {title = 'False Reporting', class = 'Misdemeanor', id = 'P.C. 6004', months = 10, fine = 750, color = 'orange'},
        [5] = {title = 'Harassment', class = 'Misdemeanor', id = 'P.C. 6005', months = 10, fine = 1000, color = 'orange'},
        [6] = {title = 'Misdemeanor Obstruction of Justice', class = 'Misdemeanor', id = 'P.C. 6006', months = 20, fine = 1000, color = 'orange'},
        [7] = {title = 'Felony Obstruction of Justice', class = 'Felony', id = 'P.C. 6007', months = 30, fine = 1800, color = 'red'},
        [8] = {title = 'Inciting a Riot', class = 'Felony', id = 'P.C. 6008', months = 25, fine = 1000, color = 'red'},
        [9] = {title = 'Rioting', class = 'Felony', id = 'P.C. 6009', months = 25, fine = 1000, color = 'red'},
        [10] = {title = 'Loitering', class = 'Infraction', id = 'P.C. 6010', months = 0, fine = 250, color = 'green'},
        [11] = {title = 'Loitering on Government Properties', class = 'Infraction', id = 'P.C. 6011', months = 0, fine = 500, color = 'green'},
        [12] = {title = 'Tampering', class = 'Misdemeanor', id = 'P.C. 6012', months = 10, fine = 500, color = 'orange'},
        [13] = {title = 'Vehicle Tampering', class = 'Misdemeanor', id = 'P.C. 6013', months = 15, fine = 750, color = 'orange'},
        [14] = {title = 'Evidence Tampering', class = 'Felony', id = 'P.C. 6014', months = 20, fine = 1000, color = 'red'},
        [15] = {title = 'Witness Tampering', class = 'Felony', id = 'P.C. 6015', months = 15, fine = 3000, color = 'red'},
        [16] = {title = 'Failure to Provide Identification', class = 'Misdemeanor', id = 'P.C. 6016', months = 15, fine = 1500, color = 'orange'},
        [17] = {title = 'Vigilantism', class = 'Felony', id = 'P.C. 6017', months = 30, fine = 1500, color = 'red'},
        [18] = {title = 'Unlawful Assembly', class = 'Misdemeanor', id = 'P.C. 6018', months = 10, fine = 750, color = 'orange'},
        [19] = {title = 'Government Corruption', class = 'Felony', id = 'P.C. 6019', months = 45, fine = 8000, color = 'red'},
        [20] = {title = 'Stalking', class = 'Felony', id = 'P.C. 6020', months = 10, fine = 1500, color = 'red'},
        [21] = {title = 'Aiding and Abetting', class = 'Felony', id = 'P.C. 6021', months = 30, fine = 5000, color = 'red'},
        [22] = {title = 'Harboring a Fugitive', class = 'Misdemeanor', id = 'P.C. 6022', months = 15, fine = 2500, color = 'orange'},
        [23] = {title = 'Public Intoxication', class = 'Infraction', id = 'P.C. 6023', months = 0, fine = 500, color = 'green'},
        [24] = {title = 'Public Indecency', class = 'Infraction', id = 'P.C. 6024', months = 10, fine = 750, color = 'green'},
        [25] = {title = 'Endangering a Government Facility', class = 'Felony', id = 'P.C. 6025', months = 50, fine = 9000, color = 'red'},
    },
    [7] = {
        [1] = {title = 'Misdemeanor Possession of Schedule 1 narcotic', class = 'Misdemeanor', id = 'P.C. 7001', months = 10, fine = 500, color = 'orange'},
        [2] = {title = 'Felony Possession of Schedule 1 narcotic', class = 'Felony', id = 'P.C. 7002', months = 20, fine = 750, color = 'red'},
        [3] = {title = 'Cultivation of Schedule 1 narcotic', class = 'Felony', id = 'P.C. 7003', months = 15, fine = 1250, color = 'red'},
        [4] = {title = 'Criminal sale of a Schedule 1 narcotic', class = 'Felony', id = 'P.C. 7004', months = 15, fine = 1000, color = 'red'},
        [5] = {title = 'Misdemeanor Possession of Schedule 2 narcotic', class = 'Misdemeanor', id = 'P.C. 7005', months = 25, fine = 1500, color = 'orange'},
        [6] = {title = 'Felony Possession of Schedule 2 narcotic', class = 'Felony', id = 'P.C. 7006', months = 40, fine = 1750, color = 'red'},
        [7] = {title = 'Cultivation of a Schedule 2 narcotic', class = 'Felony', id = 'P.C. 7007', months = 25, fine = 2250, color = 'red'},
        [8] = {title = 'Criminal Sale of a Schedule 2 narcotic', class = 'Felony', id = 'P.C. 7008', months = 20, fine = 2000, color = 'red'},
        [9] = {title = 'Sale of a controlled substance', class = 'Misdemeanor', id = 'P.C. 7009', months = 10, fine = 1000, color = 'orange'},
        [10] = {title = 'Drug Trafficking', class = 'Felony', id = 'P.C. 7010', months = 40, fine = 7000, color = 'red'},
        [11] = {title = 'Desecration of a Human Corpse', class = 'Felony', id = 'P.C. 7011', months = 20, fine = 2500, color = 'red'},
    },
    [8] = {
        [1] = {title = 'Criminal Possession of Weapon Class 1', class = 'Felony', id = 'P.C. 8001', months = 15, fine = 1000, color = 'red'},
        [2] = {title = 'Criminal Possession of Weapon Class 2', class = 'Felony', id = 'P.C. 8002', months = 20, fine = 2000, color = 'red'},
        [3] = {title = 'Criminal Possession of Weapon Class 3', class = 'Felony', id = 'P.C. 8003', months = 25, fine = 3000, color = 'red'},
        [4] = {title = 'Criminal Possession of Explosives', class = 'Felony', id = 'P.C. 8004', months = 40, fine = 4000, color = 'red'},
        [5] = {title = 'Criminal Possession of a Government Issued Firearm', class = 'Felony', id = 'P.C. 8005', months = 35, fine = 4000, color = 'red'},
        [6] = {title = 'Criminal possession of an outlawed firearm', class = 'Felony', id = 'P.C. 8006', months = 35, fine = 4000, color = 'red'},
        [7] = {title = 'Criminal Sale of Weapon Class 1', class = 'Felony', id = 'P.C. 8007', months = 20, fine = 1500, color = 'red'},
        [8] = {title = 'Criminal Sale of Weapon Class 2', class = 'Felony', id = 'P.C. 8008', months = 25, fine = 2500, color = 'red'},
        [9] = {title = 'Criminal Sale of Weapon Class 3', class = 'Felony', id = 'P.C. 8009', months = 30, fine = 3500, color = 'red'},
        [10] = {title = 'Criminal Sale of Explosives', class = 'Felony', id = 'P.C. 8010', months = 45, fine = 4500, color = 'red'},
        [11] = {title = 'Criminal Sale of Government Issued Firearm', class = 'Felony', id = 'P.C. 8011', months = 40, fine = 4500, color = 'red'},
        [12] = {title = 'Criminal Sale of Outlawed Firearm', class = 'Felony', id = 'P.C. 8012', months = 40, fine = 4500, color = 'red'},
        [13] = {title = 'Criminal Use of Weapon', class = 'Felony', id = 'P.C. 8013', months = 10, fine = 1000, color = 'red'},
        [14] = {title = 'Criminal Use of Explosives', class = 'Felony', id = 'P.C. 8014', months = 30, fine = 6000, color = 'red'},
        [15] = {title = 'Criminal Use of an Outlawed Firearm', class = 'Felony', id = 'P.C. 8015', months = 30, fine = 3000, color = 'red'},
        [16] = {title = 'Brandishing a Firearm', class = 'Misdemeanor', id = 'P.C. 8016', months = 10, fine = 500, color = 'orange'},
        [17] = {title = 'Brandishing a non firearm', class = 'Misdemeanor', id = 'P.C. 8017', months = 10, fine = 500, color = 'orange'},
        [18] = {title = 'Accomplice to Criminal Sale of a Outlawed Firearm', class = 'Felony', id = 'P.C. 8018', months = 35, fine = 3750, color = 'red'},
        [19] = {title = 'Accomplice to Criminal Sale of Government Issued Firearms', class = 'Felony', id = 'P.C. 8019', months = 35, fine = 3750, color = 'red'},
        [20] = {title = 'Accomplice to Insurrection', class = 'Felony', id = 'P.C. 8020', months = 50, fine = 15000, color = 'red'},
        [21] = {title = 'Insurrection', class = 'Felony', id = 'P.C. 8021', months = 80, fine = 20000, color = 'red'},
        [22] = {title = 'Flying into Restricted Airspace', class = 'Felony', id = 'P.C. 8022', months = 20, fine = 1500, color = 'red'},
        [23] = {title = 'Weapon Trafficking', class = 'Felony', id = 'P.C. 8023', months = 30, fine = 7000, color = 'red'},
        [24] = {title = 'Possession of Illegal Firearm Modifications', class = 'Felony', id = 'P.C. 8024', months = 10, fine = 500, color = 'red'},
    },
    [9] = {
        [1] = {title = 'First Degree Speeding', class = 'Misdemeanor', id = 'P.C. 9001', months = 0, fine = 300, color = 'orange'},
        [2] = {title = 'Second Degree Speeding', class = 'Infraction', id = 'P.C. 9002', months = 0, fine = 300, color = 'green'},
        [3] = {title = 'Third Degree Speeding', class = 'Infraction', id = 'P.C. 9003', months = 0, fine = 300, color = 'green'},
        [4] = {title = 'Driving While Intoxicated', class = 'Misdemeanor', id = 'P.C. 9004', months = 5, fine = 300, color = 'orange'},
        [5] = {title = 'Evading', class = 'Misdemeanor', id = 'P.C. 9005', months = 10, fine = 800, color = 'orange'},
        [6] = {title = 'Reckless Evading', class = 'Felony', id = 'P.C. 9006', months = 15, fine = 1600, color = 'red'},
        [7] = {title = 'Accomplice to Reckless Evading', class = 'Felony', id = 'P.C. 9007', months = 10, fine = 1400, color = 'red'},
        [8] = {title = 'Reckless Driving', class = 'Misdemeanor', id = 'P.C. 9008', months = 10, fine = 750, color = 'orange'},
        [9] = {title = 'Negligent Driving', class = 'Infraction', id = 'P.C. 9009', months = 0, fine = 300, color = 'green'},
        [10] = {title = 'Failure to Yield to Emergency Vehicle', class = 'Infraction', id = 'P.C. 9010', months = 0, fine = 600, color = 'green'},
        [11] = {title = 'Failure to Obey Traffic Control Device', class = 'Infraction', id = 'P.C. 9011', months = 0, fine = 200, color = 'green'},
        [12] = {title = 'Failure to Stop', class = 'Infraction', id = 'P.C. 9012', months = 0, fine = 45, color = 'green'},
        [13] = {title = 'Failure to Maintain Lane', class = 'Infraction', id = 'P.C. 9013', months = 0, fine = 30, color = 'green'},
        [14] = {title = 'Illegal U-Turn', class = 'Infraction', id = 'P.C. 9014', months = 0, fine = 30, color = 'green'},
        [15] = {title = 'Illegal Passing', class = 'Infraction', id = 'P.C. 9015', months = 0, fine = 30, color = 'green'},
        [16] = {title = 'Illegal Turn', class = 'Infraction', id = 'P.C. 9016', months = 0, fine = 30, color = 'green'},
        [17] = {title = 'Installing Illegal Modifications into/onto a Vehicle', class = 'Felony', id = 'P.C. 9017', months = 30, fine = 4500, color = 'red'},
        [18] = {title = 'Modified Headlights and/or Underbody Neon', class = 'Infraction', id = 'P.C. 9018', months = 0, fine = 500, color = 'green'},
        [19] = {title = 'Possession of Illegal Vehicle Modifications', class = 'Infraction', id = 'P.C. 9019', months = 0, fine = 500, color = 'green'},
        [20] = {title = 'Possession or Use of Nitrous Oxide System (NOS):', class = 'Misdemeanor', id = 'P.C. 9020', months = 10, fine = 500, color = 'orange'},
        [21] = {title = 'Unlicensed Operation of Vehicle', class = 'Infraction', id = 'P.C. 9021', months = 0, fine = 250, color = 'green'},
        [22] = {title = 'Operating a Motor Vehicle Without Proper Identification', class = 'Misdemeanor', id = 'P.C. 9022', months = 0, fine = 300, color = 'orange'},
        [23] = {title = 'Operating a Vehicle with Illegal Modifications', class = 'Misdemeanor', id = 'P.C. 9023', months = 20, fine = 3000, color = 'orange'},
        [24] = {title = 'Unauthorized Parking', class = 'Infraction', id = 'P.C. 9024', months = 0, fine = 60, color = 'green'},
        [25] = {title = 'Unlawful Use of a Motorvehicle', class = 'Misdemeanor', id = 'P.C. 9025', months = 10, fine = 750, color = 'orange'},
        [26] = {title = 'Hit and Run', class = 'Misdemeanor', id = 'P.C. 9026', months = 10, fine = 1000, color = 'orange'},
        [27] = {title = 'Felony Hit and Run', class = 'Felony', id = 'P.C. 9027', months = 25, fine = 2500, color = 'red'},
        [28] = {title = 'Street Racing', class = 'Misdemeanor', id = 'P.C. 9028', months = 15, fine = 750, color = 'orange'},
        [29] = {title = 'Street Racing Causing Injury', class = 'Felony', id = 'P.C. 9029', months = 30, fine = 1000, color = 'red'},
        [30] = {title = 'Dangerous Driving While Racing', class = 'Felony', id = 'P.C. 9030', months = 20, fine = 3000, color = 'red'},
        [31] = {title = 'Driving without Headlights or Signals', class = 'Infraction', id = 'P.C. 9031', months = 0, fine = 25, color = 'green'},
        [32] = {title = 'Piloting without Proper Licensing', class = 'Felony', id = 'P.C. 9032', months = 20, fine = 1500, color = 'red'},
    },
    [10] = {
        [1] = {title = 'Hunting in Restricted Areas', class = 'Infraction', id = 'P.C. 10001', months = 0, fine = 450, color = 'green'},
        [2] = {title = 'Hunting with a Non-Hunting Weapon', class = 'Misdemeanor', id = 'P.C. 10002', months = 10, fine = 750, color = 'orange'},
        [3] = {title = 'Hunting outside of hunting hours', class = 'Infraction', id = 'P.C. 10003', months = 0, fine = 750, color = 'green'},
        [4] = {title = 'Overhunting', class = 'Misdemeanor', id = 'P.C. 10004', months = 10, fine = 1000, color = 'orange'},
        [5] = {title = 'Unlicensed Hunting', class = 'Infraction', id = 'P.C. 10005', months = 0, fine = 450, color = 'green'},
        [6] = {title = 'Unlicensed Fishing', class = 'Infraction', id = 'P.C. 10006', months = 0, fine = 1250, color = 'green'},
        [7] = {title = 'Animal Cruelty', class = 'Misdemeanor', id = 'P.C. 10007', months = 10, fine = 450, color = 'orange'},
        [8] = {title = 'Pocession Of Endangered Species', class = 'Misdemeanor', id = 'P.C. 10008', months = 20, fine = 2500, color = 'orange'},
        [9] = {title = 'Poaching', class = 'Felony', id = 'P.C. 10009', months = 20, fine = 1250, color = 'red'},
    },
    [11] = {
        [1] = {title = 'First Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11001', months = 150, fine = 35000, color = 'black'},
        [2] = {title = 'Accomplice to First Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11002', months = 75, fine = 17500, color = 'black'},
        [3] = {title = 'Accessory to First Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11003', months = 70, fine = 16000, color = 'black'},
        [4] = {title = 'Attempted First Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11004', months = 70, fine = 17500, color = 'black'},
        [5] = {title = 'Accomplice to Attempted First Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11005', months = 55, fine = 15000, color = 'black'},
        [6] = {title = 'Accessory to Attempted First Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11006', months = 45, fine = 12500, color = 'black'},
        [7] = {title = 'First Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11007', months = 160, fine = 36000, color = 'black'},
        [8] = {title = 'Accomplice to First Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11008', months = 75, fine = 17500, color = 'black'},
        [9] = {title = 'Accessory to First Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11009', months = 70, fine = 16000, color = 'black'},
        [10] = {title = 'Attempted First Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11010', months = 80, fine = 17500, color = 'black'},
        [11] = {title = 'Accomplice to Attempted First Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11011', months = 75, fine = 15000, color = 'black'},
        [12] = {title = 'Accessory to Attempted First Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11012', months = 65, fine = 12500, color = 'black'},
        [13] = {title = 'Second Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11013', months = 100, fine = 25000, color = 'black'},
        [14] = {title = 'Accomplice to Second Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11014', months = 80, fine = 16000, color = 'black'},
        [15] = {title = 'Accessory to Second Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11015', months = 70, fine = 13500, color = 'black'},
        [16] = {title = 'Attempted Second Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11016', months = 50, fine = 14500, color = 'black'},
        [17] = {title = 'Accomplice to Attempted Second Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11017', months = 40, fine = 12500, color = 'black'},
        [18] = {title = 'Accessory to Attempted Second Degree Murder on a Peace Officer', class = 'Capital Offense', id = 'P.C. 11018', months = 35, fine = 12500, color = 'black'},
        [19] = {title = 'Second Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11019', months = 110, fine = 26000, color = 'black'},
        [20] = {title = 'Accomplice to Second Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11020', months = 60, fine = 16000, color = 'black'},
        [21] = {title = 'Accessory to Second Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11021', months = 50, fine = 13500, color = 'black'},
        [22] = {title = 'Attempted Second Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11022', months = 60, fine = 14500, color = 'black'},
        [23] = {title = 'Accomplice to Attempted Second Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11023', months = 40, fine = 12500, color = 'black'},
        [24] = {title = 'Accessory to Attempted Second Degree Murder of a Government Official', class = 'Capital Offense', id = 'P.C. 11024', months = 35, fine = 10000, color = 'black'},
        [25] = {title = 'Kidnapping of a Peace Officer', class = 'Capital Offense', id = 'P.C. 11025', months = 25, fine = 9500, color = 'black'},
        [26] = {title = 'Accomplice to Kidnapping a Peace Officer', class = 'Capital Offense', id = 'P.C. 11026', months = 20, fine = 6750, color = 'black'},
        [27] = {title = 'Accessory to Kidnapping a Peace Officer', class = 'Capital Offense', id = 'P.C. 11027', months = 15, fine = 5000, color = 'black'},
        [28] = {title = 'Attempted Kidnapping of a Peace Officer', class = 'Capital Offense', id = 'P.C. 11028', months = 35, fine = 6750, color = 'black'},
        [29] = {title = 'Kidnapping of a Government Official', class = 'Capital Offense', id = 'P.C. 11029', months = 30, fine = 9500, color = 'black'},
        [30] = {title = 'Accomplice to Kidnapping a Government Official', class = 'Capital Offense', id = 'P.C. 11030', months = 20, fine = 6750, color = 'black'},
        [31] = {title = 'Accessory to Kidnapping a Government Official ', class = 'Capital Offense', id = 'P.C. 11031', months = 15, fine = 5000, color = 'black'},
        [32] = {title = 'Atttempted Kidnapping of a Government Official', class = 'Capital Offense', id = 'P.C. 11032', months = 30, fine = 6750, color = 'black'},
        [32] = {title = 'Terrorism', class = 'Capital Offense', id = 'P.C. 11032', months = 175, fine = 75000, color = 'black'},
        [33] = {title = 'Accomplice to Terrorism', class = 'Capital Offense', id = 'P.C. 11033', months = 150, fine = 50000, color = 'black'},
        [34] = {title = 'Accessory to Terrorism', class = 'Capital Offense', id = 'P.C. 11034', months = 110, fine = 37500, color = 'black'},
    }
}


Config.PoliceJobs = {
    ['police'] = true,
    ['fib'] = true,
    ["sasp"] = true,
    ['ranger'] = true,
    ['bcso'] = true,
    
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
    ['judge'] = true,
    ['doj']=true,
}

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[10] = true,
	},
	['fib'] = {
		[5] = true,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = { 
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}
